language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/waiter_database

node_js:  
  - "8.9.4"

before_script: 
  - psql -c 'create database  registration_app_database;' -U postgres
  - psql -U postgres -d registration_app_database -a -f sql/table.sql
  - psql -U postgres -d registration_app_database -a -f sql/insertEmployees.sql

addons:
    apt:
    packages:
    - postgresql-server-dev-9.2